services:
  weblab-f11:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weblab-f11
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
      - PORT=3000
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./data:/app/data
